name: Sync Fork with Upstream

on:
  schedule:
    # 每天 UTC 时间 0 点运行（可根据需要调整）
    - cron: '0 0 * * *'
  # 也可以手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录

      - name: Add upstream remote
        run: |
          git remote add upstream ${{ github.event.repository.parent.git_url }}
          git fetch upstream
          
      - name: Merge upstream changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout ${{ github.event.repository.default_branch }}
          git merge --no-edit upstream/${{ github.event.repository.parent.default_branch }}
          git push origin ${{ github.event.repository.default_branch }}